### PR TITLE
Fixes for nulldb

### LINKED ISSUE #259: Nulldb master issue
Creating this to track bugs in nulldb. Update as issues are found.

### Delete not removing docs completely
- [x] fixed by #260
```
INFO[2017-07-14T12:08:33-04:00] Removed service dittoSvc1                     file=manager.go line=624
ERRO[2017-07-14T12:08:34-04:00] Could not get service "b3260d40-7b94-40d9-abca-fdad4692c34a"  error="Object not found" file=manager.go line=344
ERRO[2017-07-14T12:08:35-04:00] Could not get service "b3260d40-7b94-40d9-abca-fdad4692c34a"  error="Object not found" file=manager.go line=344
ERRO[2017-07-14T12:08:36-04:00] Could not get service "b3260d40-7b94-40d9-abca-fdad4692c34a"  error="Object not found" file=manager.go line=344
ERRO[2017-07-14T12:08:37-04:00] Could not get service "b3260d40-7b94-40d9-abca-fdad4692c34a"  error="Object not found" file=manager.go line=344
```

### PR DESCRIPTION
**Pull request by adamschaub**
A rewrite of nulldb:

1. Make it more reusable/easier to modify in the future
2. Fix some inconsistencies (wrong errors returned)
3. Give it proper CAS handling

Fixes #259 

## TODO 
- [x] Fix tests. The apiserver tests are super potato right now. Could warrant it's own PR. Could warrant JUST DELETING THEM AAGGHHh

### CODE REVIEW

**Comment by mikeynap** [comment]
Damn, someone putting in time for NullDB, it really is Christmas.

File: database/nulldb.go [hunk 1]
```diff
@@ -483,328 +203,541 @@ func query(mdaters []model.Metadataer, m model.Metadataer, filters map[string]in
...
+	var obj model.ServiceOperation
+	err := n.deleteByNameOrID(&obj, ServiceOperationType, m)
+	return err
+}
+
+func (n *NullDB) DeleteSecret(s model.Secret) error {
+	return n.deleteByNameOrID(s, SecretType, n.secretName(s))
+}
+
+// UPDATE
```
Comment (mikeynap) [inline database/nulldb.go]: ha
