### PR TITLE
Fixes edge case causing PluginLogger to panic

### LINKED ISSUE #421: Plugin logger panic
##### Description

If anything causes a new PluginClient to not be initialized properly, we can't use the plugin logger because it hasn't been initialized yet. We need to simply print to STDERR.

### PR DESCRIPTION
**Pull request by rfliegerallison**
### PR checklist

- [x] Follows the [Developer Guide](https://sigma-dev.github.io/sigma/docs/developer-guide/).
- [x] Filed the PR against the correct branch?

### Change log

Fixes logging in the main function so the logger isn't called when it failed to be instantiated.

### Notes

Resolves #421 

### TODO

`latest` containers need to be updated to use these changes.

### CODE REVIEW

File: examples/coffee-run/coffee-orders/main.go [hunk 1]
```diff
@@ -119,10 +121,10 @@ func (c *CoffeeOrders) update(op pc.PluginArg) error {
 
 func main() {
 	c, err := New()
-	c.log.Println("Welcome to the Coffee Orders Plugin")
 	if err != nil {
-		c.log.Fatalf("Failed to Initialize: %v", err)
+		fmt.Fprintf(os.Stderr, "Failed to Initialize: %v", err)
```
Comment (mikeynap) [inline examples/coffee-run/coffee-orders/main.go]: gotta add an exit here or else we'll still panic :0

File: examples/coffee-run/coffee-prices/main.go [hunk 2]
```diff
@@ -136,10 +138,10 @@ func (c *CoffeePrices) update(op pc.PluginArg) error {
 
 func main() {
 	c, err := New()
-	c.log.Println("Welcome to the Coffee Prices Plugin")
 	if err != nil {
-		c.log.Fatalf("Failed to Initialize: %v", err)
+		fmt.Fprintf(os.Stderr, "Failed to Initialize: %v", err)
```
Comment (mikeynap) [inline examples/coffee-run/coffee-prices/main.go]: Unfortunately I think you gotta do this for all the plugins... feels bad man

File: examples/coffee-run/coffee-orders/main.go (hunk 1 above)
Comment (rfliegerallison) [reply examples/coffee-run/coffee-orders/main.go]: if i `return` that should be fine, right?
